version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: web.Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      - POSTGRES_DB=eventdb
      - POSTGRES_USER=eventuser
      - POSTGRES_PASSWORD=eventpass
    ports:
      - "5432:5432"

  redis:
    container_name: redis
    restart: always
    image: redis:alpine
    ports:
      - "6379:6379"

  worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    depends_on:
      - redis
  
  beat:
    build:
      context: .
      dockerfile: beat.Dockerfile
    depends_on:
      - redis