# Generated by Django 5.1.6 on 2025-02-11 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventlogs", "0001_initial"),
        ("triggers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventlog",
            name="trigger",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="triggers.trigger"
            ),
        ),
    ]
