# Generated by Django 5.1.6 on 2025-02-11 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventlogs", "0003_alter_eventlog_trigger"),
        ("triggers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventlog",
            name="trigger_data",
            field=models.JSONField(default="null"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="eventlog",
            name="trigger",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="triggers.trigger",
            ),
        ),
    ]
