# Generated by Django 5.1.6 on 2025-02-11 13:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlogs', '0004_eventlog_trigger_data_alter_eventlog_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
